//Guests
export const SEND_EMAIL = 'SEND_EMAIL'
export const REMOVE_CONTACT_RESPONSE = 'REMOVE_CONTACT_RESPONSE'
export const CONTACT_ERROR = "CONTACT_ERROR"

//Users
export const REGISTER = "REGISTER"
export const USER_ERROR = "USER_ERROR"
export const REMOVE_USER_RESPONSE = "REMOVE_USER_RESPONSE"
export const RESET_PASSWORD = "RESET_PASSWORD"
export const USER_PROFILE = "USER_PROFILE"
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE"

//Auth
export const GET_USER ="GET_USER"
export const LOGOUT = "LOGOUT"
export const LOGIN = "LOGIN"
export const REMOVE_AUTH_RESPONSE = "REMOVE_AUTH_RESPONSE"
export const AUTH_ERROR = "AUTH_ERROR"

//Services
export const CREATE_CERTIFICATE_OF_INDIGENCY = "CREATE_CERTIFICATE_OF_INDIGENCY"
export const REMOVE_SERVICE_RESPONSE = "REMOVE_SERVICE_RESPONSE"
export const GET_USER_APPLICATIONS = "GET_USER_APPLICATIONS"
export const CREATE_CERTIFICATE_OF_RESIDENCY = "CREATE_CERTIFICATE_OF_RESIDENCY"
export const CREATE_CEDULA = "CREATE_CEDULA"
export const CREATE_BARANGAY_CLEARANCE = "CREATE_BARANGAY_CLEARANCE"
export const CREATE_BUSINESS_CLEARANCE = "CREATE_BUSINESS_CLEARANCE"
export const CREATE_ID_APPLICATION = "CREATE_ID_APPLICATION"

//Services(Admin)
export const DELETE_RESIDENT = "DELETE_RESIDENT"
export const ADD_EQUIPMENT = "ADD_EQUIPMENT"
export const GET_ALL_EQUIPMENT ="GET_ALL_EQUIPMENT"
export const DELETE_EQUIPMENT = "DELETE_EQUIPMENT"
export const UPDATE_VACCINATION_DATA = "UPDATE_VACCINATION_DATA"
export const VACCINATION_DATA = "VACCINATION_DATA"
export const GET_ALL_USERS = "GET_ALL_USERS"
export const UPDATE_SUPPLY = "UPDATE_SUPPLY"
export const DELETE_SUPPLY = "DELETE_SUPPLY"
export const ADD_SUPPLY = "ADD_SUPPLY"
export const GET_SUPPLIES = "GET_SUPPLIES"
export const GET_SUPPLY = "GET_SUPPLY"
export const GET_SALES = "GET_SALES"
export const GET_UNVERIFIED = "GET_UNVERIFIED"
export const VERIFY_USER = "VERIFY_USER"
export const REJECT_VERIFICATION = "REJECT_VERIFICATION" 

//Ayuda(Admin)
export const GET_AYUDA_DATA = "GET_AYUDA_DATA"
export const CREATE_AYUDA_PROGRAM = "CREATE_AYUDA_PROGRAM"
export const REMOVE_ADMIN_RESPONSE = "REMOVE_ADMIN_RESPONSE"
export const GET_AYUDA_PROGRAMS = "GET_AYUDA_PROGRAMS"
export const DELETE_AYUDA_PROGRAM = "DELETE_AYUDA_PROGRAM"
export const GET_RECIPIENTS = "GET_RECIPIENTS"
export const GET_ALL_APPLICATIONS = "GET_ALL_APPLICATIONS"
export const UPDATE_APPLICATION = "UPDATE_APPLICATION"
export const UPLOAD_PROOF = "UPLOAD_PROOF"
export const SET_RECIPIENT_STATUS = "SET_RECIPIENT_STATUS"
export const GET_RESIDENTS = "GET_RESIDENTS"
export const GET_RESIDENT = "GET_RESIDENT"
export const UPDATE_RESIDENT = "UPDATE_RESIDENT"

